- name: set up to do app
  hosts: webservers
  remote_user: ec2-user

  tasks:
  - name: install git
    ansible.builtin.yum:
      
      name: git
      state: latest
      become: yes
 
  - name: install python
    ansible.builtin.yum:
      
      name: python3
      state: latest
      become: yes 

  - name: install poetry
    ansible.builtin.shell: curl -sSL https://install.python-poetry.org | python3 -
    args:
      creates: /home/ec2-user/.local/bin/poetry 

  - name: create directory
    ansible.builtin.file:
      path: /opt/todoapp
      state: directory
      owner: ec2-user