- name: set up to do app
  hosts: webservers
  remote_user: ec2-user

  tasks:
  - name: install git
    ansible.builtin.yum:
      
      name: git
      state: latest
      become: yes
 
  - name: install python
    ansible.builtin.yum:
      
      name: python3
      state: latest
      become: yes   