name: Continuous Integration 
on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
      
jobs: 
 job1: 
  name: Job-One 
  runs-on: ubuntu-latest 
  steps: 
  - uses: actions/checkout@v2 

  - name: Builds the tests
    run: docker build --target test --tag my-test-image .

  - name: Runs the tests
    run: docker run --env-file .env.test my-test-image

 job2:
  if: github.event_name == 'push' && github.ref == 'refs/heads/exercise8'
  needs: job1
  name: Job-Two
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2 
  
  - name: Login to Docker Hub
    uses: docker/login-action@v2
    with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

  - name: docker build
    run: docker build --target production --tag kelliep/my-todo-app .
  - name: docker push
    run: docker push kelliep/my-todo-app:latest

 
 job3:
    if: github.event_name == 'push' && github.ref == 'refs/heads/exercise8'
    needs: job2
    name: heroku deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
  
  
