name: Continuous Integration 
on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
jobs: 
 build: 
  name: Build and test 
  runs-on: ubuntu-latest 
  steps: 
  - uses: actions/checkout@v2 

  - name: Builds the tests
    run: docker build --target test --tag my-test-image .

  - name: Runs the tests
    run: docker run --env-file .env.test my-test-image
